
# coding: utf-8

# In[ ]:

#SUBS
def find_substring(orig_string, substring):
    instances = []
    for i in range(len(orig_string)):
        test_string = orig_string[i:len(substring) + i]
        if substring == test_string:
            instances.append(str(i + 1))

    return ' '.join(instances)


def main():
    orig_string = 'GGAGCTAAACGACCTAGCTAAAAGCTAAACCCAGCTAAAAGCTAAAGCCTGTAGCGCTACCAGCTAAAGCAGCTAAACTACGATAGCTAAAAGCTAAAAGCTAAAAGCTAAAGTGCAGCTAAAAGCTAAAAAAGCTAAAAGCTAAAGCTCCGAGCTAAAAGCTAAAGATAGTTGTGGCCGGCCTAAGCTAAAACCGGTTAGCTAAAAGCTAAACAGCTAAAATGCAGCTAAACGTCTTTGTTAGCTAAATTGGCAGCTAAAAAGCTAAACCGGAGCTAAATGAAGCTAAAAGCTAAAAGCTAAAATAGCTAAAAGGTGACCCCAGCTAAACACCGGAAGTAGCTAAATAGCTAAACCGGAGCTAAAAGCTAAAAGTAGCTAAAAGCTAAAAAGCTAAAAGCTAAAGCTTTGGGAGCTAAACTAGGTTAGCTAAATTACGCAGCTAAAAAACTGAGCTAAAAGCTAAAATCACAGCTAAAACAGCTAAATAGCTAAATCAGCTAAACCCAACGAGCTAAAGATGAAGCTAAAGCAGCTAAAAGCTAAATAAGAACAGCTAAAAGCTAAAAGCTAAACTAGCTAAAAAGAGCTAAAAGCTAAAATGGAGCTAAAAGCTAAACTAAGCTAAATCTCAGCTAAACGTGATGTGGAGCTAAAGGGAGCTAAACATAGCTAAAAAGAAGCTAAAATTTAGCTAAAGGGACAAGCTAAAAGCTAAAAAGCTAAATCGCGAGCTAAAAGCTAAAGAGAGCTAAAACCGCAGCTAAAAGCTAAAAGCTAAAGAAGCTAAACGAGCTAAAAGTAGCTAAAGAGCTAAACGAAAGCTAAAGAAGCTAAAGGTAATCGAAAGCTAAATAAGCTAAAAGCTAAAAAGCTAAATATAGCTAAAAGCTAAAAGCTAAATAGCTAAACATTGCTCAGCTAAAAGCTAAACGAGCTAAACAAGCTAAACTAGCTAAA'
    substring = 'AGCTAAAAG'
    print (find_substring(orig_string, substring))


if __name__ == "__main__":
    main()

